<?php

namespace Jmlamo\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    /**
     * @param int $maxPrice
     * @return array
     */
    public function findAllByMaxParice($maxPrice)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM JmlamoDemoBundle:Product p
                WHERE p.price <= :maxPrice
                ORDER BY p.price ASC'
            )
            ->setParameter('maxPrice', $maxPrice)
            ->getResult();
    }
    
    /**
     * @param integer $id
     * @return Product|null
     */
    public function findOneByIdJoinedToCategory($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, c
                FROM JmlamoDemoBundle:Product p
                LEFT JOIN p.category c
                WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
